config/routes.rb
Rails.application.routes.draw do
  resources :involved_companies
  resources :genres
  resources :platforms
  resources :games
  resources :companies
  resources :critics
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/involved_company.rb
class InvolvedCompany < ApplicationRecord
  belongs_to :company
  belongs_to :game
end

app/controllers/involved_companies_controller.rb
class InvolvedCompaniesController < ApplicationController
  before_action :set_involved_company, only: %i[ show edit update destroy ]

  # GET /involved_companies or /involved_companies.json
  def index
    @involved_companies = InvolvedCompany.all
  end

  # GET /involved_companies/1 or /involved_companies/1.json
  def show
  end

  # GET /involved_companies/new
  def new
    @involved_company = InvolvedCompany.new
  end

  # GET /involved_companies/1/edit
  def edit
  end

  # POST /involved_companies or /involved_companies.json
  def create
    @involved_company = InvolvedCompany.new(involved_company_params)

    respond_to do |format|
      if @involved_company.save
        format.html { redirect_to involved_company_url(@involved_company), notice: "Involved company was successfully created." }
        format.json { render :show, status: :created, location: @involved_company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @involved_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /involved_companies/1 or /involved_companies/1.json
  def update
    respond_to do |format|
      if @involved_company.update(involved_company_params)
        format.html { redirect_to involved_company_url(@involved_company), notice: "Involved company was successfully updated." }
        format.json { render :show, status: :ok, location: @involved_company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @involved_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /involved_companies/1 or /involved_companies/1.json
  def destroy
    @involved_company.destroy

    respond_to do |format|
      format.html { redirect_to involved_companies_url, notice: "Involved company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_involved_company
      @involved_company = InvolvedCompany.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def involved_company_params
      params.require(:involved_company).permit(:company_id, :game_id, :developer, :publisher)
    end
end

app/helpers/involved_companies_helper.rb
module InvolvedCompaniesHelper
end

app/views/involved_companies/_form.html.erb
<%= form_with(model: involved_company) do |form| %>
  <% if involved_company.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(involved_company.errors.count, "error") %> prohibited this involved_company from being saved:</h2>

      <ul>
        <% involved_company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :company_id, style: "display: block" %>
    <%= form.text_field :company_id %>
  </div>

  <div>
    <%= form.label :game_id, style: "display: block" %>
    <%= form.text_field :game_id %>
  </div>

  <div>
    <%= form.label :developer, style: "display: block" %>
    <%= form.check_box :developer %>
  </div>

  <div>
    <%= form.label :publisher, style: "display: block" %>
    <%= form.check_box :publisher %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/involved_companies/_involved_company.html.erb
<div id="<%= dom_id involved_company %>">
  <p>
    <strong>Company:</strong>
    <%= involved_company.company_id %>
  </p>

  <p>
    <strong>Game:</strong>
    <%= involved_company.game_id %>
  </p>

  <p>
    <strong>Developer:</strong>
    <%= involved_company.developer %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= involved_company.publisher %>
  </p>

</div>

app/views/involved_companies/edit.html.erb
<h1>Editing involved company</h1>

<%= render "form", involved_company: @involved_company %>

<br>

<div>
  <%= link_to "Show this involved company", @involved_company %> |
  <%= link_to "Back to involved companies", involved_companies_path %>
</div>

app/views/involved_companies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Involved companies</h1>

<div id="involved_companies">
  <% @involved_companies.each do |involved_company| %>
    <%= render involved_company %>
    <p>
      <%= link_to "Show this involved company", involved_company %>
    </p>
  <% end %>
</div>

<%= link_to "New involved company", new_involved_company_path %>

app/views/involved_companies/new.html.erb
<h1>New involved company</h1>

<%= render "form", involved_company: @involved_company %>

<br>

<div>
  <%= link_to "Back to involved companies", involved_companies_path %>
</div>

app/views/involved_companies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @involved_company %>

<div>
  <%= link_to "Edit this involved company", edit_involved_company_path(@involved_company) %> |
  <%= link_to "Back to involved companies", involved_companies_path %>

  <%= button_to "Destroy this involved company", @involved_company, method: :delete %>
</div>